language: node_js
branches:
  only:
    - master
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
jobs:
  include:
    - stage: test
      node_js:
        - -12
        - -13
        - -14
        - -15
